use_frameworks!

project 'TunnelSandbox', 'QA' => :release
target 'TunnelSandbox' do
  pod 'SBTUITestTunnelServer'
end

target 'TunnelSandboxUITests' do
  pod 'SBTUITestTunnelClient'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name == 'QA' # the name of your build configuration
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'ENABLE_UITUNNEL=1']
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = ['$(inherited)', 'ENABLE_UITUNNEL']
          end
      end
  end
end